brain_two/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from .views import (
    todo_list_view,
    todo_list_detail,
    todo_list_create_view,
    todo_list_update,
    delete_todo_list,
    todo_item_create,
    todo_item_update,
)

app_name = "todos"

urlpatterns = [
    path("", todo_list_view, name="todo_list_list"),
    path("<int:id>/", todo_list_detail, name="todo_list_detail"),
    path("create/", todo_list_create_view, name="todo_list_create"),
    path("<int:id>/edit/", todo_list_update, name="todo_list_update"),
    path("<int:id>/delete/", delete_todo_list, name="todo_list_delete"),
    path("items/create/", todo_item_create, name="todo_item_create"),
    path("items/<int:id>/edit/", todo_item_update, name="todo_item_update"),
]

todos/models.py
from django.db import models
from django.utils import timezone

from django.apps import apps

class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(blank=True, null=True)  # Optional due_date
    is_completed = models.BooleanField(
        default=False
    )  # Default is_completed to False
    list = models.ForeignKey(
        "todos.TodoList", related_name="items", on_delete=models.CASCADE
    )  # ForeignKey relationship with TodoList

todos/forms.py
from django.forms import ModelForm
from todos.models import TodoList, TodoItem


class TodoListForm(ModelForm):
    class Meta:
        model = TodoList
        fields = [
            'name'
        ]


class TodoItemForm(ModelForm):
    class Meta:
        model = TodoItem
        fields = [
            'task',
            'due_date',
            'is_completed',
            'list'
        ]

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import TodoList, TodoItem
from django import forms
from .forms import TodoItemForm, TodoListForm

# Create your views here.


def todo_list_view(request):
    todo_lists = TodoList.objects.all()
    return render(request, "todos/todo_list.html", {"todo_lists": todo_lists})


def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    todo_items = todo_list.items.all()
    return render(
        request,
        "todos/todo_list_detail.html",
        {
            "todo_list": todo_list,
            "todo_items": todo_items,
        },
    )


def todo_list_create_view(request):
    class TodoListForm(forms.ModelForm):
        class Meta:
            model = TodoList
            fields = ["name"]

    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            party = form.save()
            return redirect(
                "todos:todo_list_detail", party.id
            )  # Redirect to the list view
    else:
        form = TodoListForm()
    return render(request, "todos/todo_list_create.html", {"form": form})


def todo_list_update(request, id):
    todo_list = get_object_or_404(TodoList, id=id)

    class TodoListForm(forms.ModelForm):
        class Meta:
            model = TodoList
            fields = ["name"]

    if request.method == "POST":
        form = TodoListForm(request.POST, instance=todo_list)
        if form.is_valid():
            form.save()
            return redirect(
                "todos:todo_list_detail", id=id
            )  # Redirect to the detail view
    else:
        form = TodoListForm(instance=todo_list)

    return render(request, "todos/todo_list_update.html", {"form": form})


def delete_todo_list(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    if request.method == "POST":
        todo_list.delete()
        return redirect("todos:todo_list_list")

    return render(request, "todos/delete_todo_list.html")


def todo_item_create(request):
    if request.method == "POST":
        form = TodoItemForm(request.POST)
        print(request)
        if form.is_valid():
            item = form.save()
            return redirect("todos:todo_list_detail", id=item.list.id)
    else:
        form = TodoItemForm()
    return render(request, "todos/todo_item_create.html", {"form": form})


def todo_item_update(request, id):
    todo_item = get_object_or_404(TodoItem, id=id)
    if request.method == "POST":
        form = TodoItemForm(request.POST, instance=todo_item)
        if form.is_valid():
            item = form.save()
            return redirect("todos:todo_list_detail", id=item.list.id)
    else:
        form = TodoItemForm(instance=todo_item)
    return render(request, "todos/todo_item_update.html", {"form": form})

todos/templates/todos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Todo App{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'todos:todo_list_list' %}">Home</a></li>
            <li><a href="{% url 'todos:todo_list_create' %}">Create Todo List</a></li>
            <li><a href="{% url 'todos:todo_item_create' %}">Create Todo Item</a></li>
        </ul>
    </nav>
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

todos/templates/todos/delete_todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Todo List</title>
</head>
<body>
    <main>
        <div>
            <h1>Are you sure?</h1>
            <form method="post">
                {% csrf_token %}
                <button>Delete</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_item_create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Add Item</title>
    </head>
    <body>
        <header>
        <nav>
            <a href="{% url 'todos:todo_list_list' %}">Back to Todo Lists</a>
        </nav>
        </header>
        <main>
            <div>
                <h1>Create a new item</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/todo_item_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Item</title>
</head>
<body>
        <header>
        <nav>
            <a href="{% url 'todos:todo_list_list' %}">Back to Todo Lists</a>
        </nav>
        </header>
    <main>
        <div>
            <h1>Update item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'todos:todo_list_list' %}">Home</a></li>
            <li><a href="{% url 'todos:todo_list_create' %}">Create Todo List</a></li>
            <li><a href="{% url 'todos:todo_item_create' %}">Create Todo Item</a></li>
        </ul>
    </nav>
    <main>
        <div>
            <h1>My Lists</h1>

            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_list in todo_lists %}
                    <tr>
                        <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
                        <td>{{ todo_list.items.count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_list_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a new list</title>
</head>
<body>
        <header>
        <nav>
            <a href="{% url 'todos:todo_list_list' %}">Back to Todo Lists</a>
        </nav>
        </header>
    <main>
        <div>
            <h1>Create a new list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_list_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ todo_list.name }}</title>
</head>
<body>
        <header>
        <nav>
            <a href="{% url 'todos:todo_list_list' %}">Back to Todo Lists</a>
        </nav>
        </header>
    <main>
        <div>
            <h1>{{ todo_list.name }}</h1>
            <p><a href="{% url 'todos:todo_list_update' todo_list.id %}">Edit To Do</a></p>
            <p><a href="{% url 'todos:todo_list_delete' todo_list.id %}">Delete</a></p>
            <p><a href="{% url 'todos:todo_item_create' %}">Create a new item</a></p>
            <h2>Tasks</h2>
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due date</th>
                        <th>Complete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in todo_items %}
                        <tr>
                            <td><a href="{% url 'todos:todo_item_update' item.id %}">{{ item.task }}</a></td>
                            <td>{{ item.due_date }}</td>
                            <td>{{ item.is_completed }}</td>
                            <td><a href="{% url 'todos:todo_item_update' item.id %}">Edit</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_list_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Todo List</title>
</head>
<body>
        <header>
        <nav>
            <a href="{% url 'todos:todo_list_list' %}">Back to Todo Lists</a>
        </nav>
        </header>
    <main>
        <div>
            <h1>Update Todo List</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
</body>
</html>